### PR TITLE
Upgraded project files to .NET 6

### PR DESCRIPTION
**Pull request by dasblinkenlight**
- Updated nuget dependencies
- Worked around VS 2022's finding antlr-generated code twice
- Updated unit test template project to use .NET 6

### CODE REVIEW

**Comment by dasblinkenlight** [comment]
I verified that the code compiles and all 320 unit tests pass on a Mac M1 hardware running arm64 .NET 6.0.6.

**Comment by dasblinkenlight** [comment]
I pushed a fix for the failing build items to my fork. Do I need to do anything else to have the system re-run the CI?

**Comment by dasblinkenlight** [comment]
Ubuntu tests appear to be stuck. Is there any visibility into what's happening?

**Comment by dasblinkenlight** [comment]
...I guess it died again, I don't know what's going on. The other two platforms finished w/no issues on the first try.

**Comment by dasblinkenlight** [comment]
Let's see if the third change fixes the hang.

**Comment by ankushdesai** [comment]
Hi @dasblinkenlight, it seems like there is a bug in the PR. I will look into this tomorrow or on Monday and get back to you.

**Comment by dasblinkenlight** [comment]
@ankushdesai There's a chance that it has to do with me upgrading to Coyote 1.7.5. When I rolled it back to 1.0.5 the tests ran much faster on my computer. I think after the rollback the CI will run faster - at least on Mac and Windows (two successful runs took 44 minutes to an hour, vs. the more common 15..20 minutes).

**Comment by dasblinkenlight** [comment]
Could you please approve one more rerun w/the old coyote library?

**Comment by dasblinkenlight** [comment]
Do you have any update on running the latest workflow? There's a good chance it's going to run now, because I went back to the version of Coyote that the project is currently using.

**Comment by dasblinkenlight** [comment]
@ankushdesai Could you please approve a rerun to see if rolling back to the current version of Coyote fixes the problem?

**Comment by ankushdesai** [comment]
Moving to .net6 would also require upgrading to coyote that supports version .net6.0. Your changes by itself wont work. We working on porting P to .Net6 and will release the new version in a couple of weeks. Thanks for the help!

**Pull request closed without merging**
