### PR TITLE
Update PLogFormatter to new IActorRuntimeLog.

### PR DESCRIPTION
**Pull request by lovettchris**
**Don't merge this until the next Coyote update...** I'm just giving folks a heads up... `IActorRuntimeLogFormatter` is going away.  You can still implement your own entirely custom `IActorRuntimeLog` like we did with the `ActorRuntimeLogGraphBuilder`, or you can subclass  a new "text logging" implementation of this interface called `ActorRuntimeLogTextFormatter`.  The next coyote update also provides a new "--xml-trace" option which uses a new `IActorRuntimeLog` implementation called `ActorRuntimeLogXmlFormatter`.  This replaces the old crufty *.pstrace files with a much more machine readable xml format which might also be handy for any tooling you build around these logs.

### CODE REVIEW

**Comment by ankushdesai** [comment]
Thanks @lovettchris!
I had a request, @pdeligia can we also include the suggested change of adding `Event` as a payload to the log functions instead of just `eventName`. Then one can log whatever information information they need for the event (for P the attached payload).

**Comment by lovettchris** [comment]
@ankushdesai , Event e is done.  In the process I removed the code that was doing stateName.Split(".").Last() and eventName..Split(".").Last().  This kind of thing will lead to ambiguous logs is the "Tail" part of a name is the same across two events or states.  For example, you might have "Microsoft.Samples.CoffeeMachine.Init" state and the "Microsoft.Samples.SafetyMonitor.Init" and you don't want to confuse these two states just because they both have the same name "Init".  Same goes for events.

**Comment by ankushdesai** [comment]
@lovettchris Thanks for your changes.
But can you revert your changes that removed the Split(".") operation.

> Assuming the names are local to the Machine Type is not always correct either, especially for Events which might be defined outside the class, e.g. global events like "Microsoft.Coyote.Actors.HaltEvent" will not have the same base name as your custom StateMachine type.

In the context of P language, states are always enclosed inside a machine and also all events are always global events. Hence, that change was valid and is important for generating readable P traces.

If we remove `Split(".")` then the log statements refer to events in generated code with `Microsoft.*` which does not really exist in the P language level and confuses the developers.

The build is failing right now as the regressions are failing. If you cannot fix these, would it be possible for you to merge your changes in a branch so that I can work on that branch and then merge it into the master.

Thanks again for this PR.

**Comment by lovettchris** [comment]
@ankushdesai , done, short names are back.  Doing so for the new strongly typed "Event e" arguments required copy/paste actual `ActorRuntimeLogTextFormatter` implementations over to this class.  Note, I have not tested this works correctly, but the copy past was pretty mechanical so it should work. You could of course copy all the implementation from `ActorRuntimeLogTextFormatter`  and go to town with changing the actual text formatting to whatever you want...

**Comment by lovettchris** [comment]
Ok, now I have tested that it works, on the TwoPhaseCommit example, here's the log.
[TwoPhaseCommit_0_0.txt](https://github.com/p-org/P/files/4132723/TwoPhaseCommit_0_0.txt)

**Comment by ankushdesai** [comment]
Thanks @lovettchris , I will take it from here and fix the regressions that are failing.

**Pull request merged**
