### PR TITLE
[Docs] Update P GitHub pages to the new version

### PR DESCRIPTION
**Pull request by aman-goel**
Hi @ankushdesai,

Sharing this PR for primarily updating P Github pages to the new version.
Updates include:
- Updating P GitHub pages to the new P 2.0 version CLI
- Minor typo corrections to Tutorial examples
- Corrects replaying traces in P 2.0 version
- Improves how foreign files are imported in P

Feel free to share suggestions.

--
@aman-goel

### CODE REVIEW

**Review by ankushdesai — CHANGES_REQUESTED** [review]
Please update the documentation based on our discussion.

**Comment by ankushdesai** [comment]
@aman-goel can I also request you to pull in changes from the master branch.

**Comment by aman-goel** [comment]
> @aman-goel can I also request you to pull in changes from the master branch.

I suggest we merge changes from master branch through a separate PR.
I will do this through a fresh PR once this one is merged.

**Comment by aman-goel** [comment]
@ankushdesai 
I have completed adding changes relating to this PR.
Let me know how it looks.

Once this PR is merged, I will share a separate PR to fetch changes from master.

**Review by ankushdesai — APPROVED** [review]

**Comment by aman-goel** [comment]
> @aman-goel can I also request you to pull in changes from the master branch.

Relevant PR: https://github.com/p-org/P/pull/561

**Pull request merged**
